[colors.bright]
black = "0x666585"
blue = "0x326ccc"
cyan = "0x63f2f1"
green = "0x62d196"
magenta = "0x906cff"
red = "0xff5458"
white = "0x96a3dc"
yellow = "0xffb378"

[colors.cursor]
cursor = "#caca00"
text = "#000000"

[colors.normal]
black = "0x201e33"
blue = "0x91ddff"
cyan = "0xaaffe4"
green = "0x95ffa4"
magenta = "0xc991e1"
red = "0xff8080"
white = "0xbbd3f7"
yellow = "0xffe9aa"

[colors.primary]
background = "0x1e1c31"
foreground = "0xcbe3e7"

[font]
size = 14

[font.normal]
family = "IosevkaTerm Nerd Font"
style = "ExtraLight"

[[keyboard.bindings]]
key = "N"
mods = "Command"

[keyboard.bindings.command]
args = ["-nb", "io.alacritty"]
program = "open"

[[keyboard.bindings]]
action = "ScrollPageUp"
key = "K"
mods = "Control"

[[keyboard.bindings]]
action = "ScrollPageDown"
key = "J"
mods = "Control"

[scrolling]
history = 100000
multiplier = 3

[window]
decorations = "none"
dynamic_padding = true
opacity = 0.92
startup_mode = "Maximized"

[window.padding]
x = 30
y = 20
